name: "Pull Request Labeler"
on: [push]
- pull_request_target

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas
        pip install numpy
    - run: sudo apt update
    - run: sudo apt install inotify-tools
    - run: inotifywait -mr /home/runner/work/git-client-plugin/git-client-plugin/ --format '%T;%w;%f;%e' --timefmt %T -o /home/runner/inotify-logs.csv & echo 'optimizing-ci-builds'
    - run: touch starting_triage_uses-labeler_9
    - run: rm starting_triage_uses-labeler_9
    - uses: actions/labeler@v4
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
    - run: touch starting_finished_finished_8979874
      if: always()
    - run: rm starting_finished_finished_8979874
      if: always()
    - name: Execute py script # run file
      if: always()
      run: |
        python .github/workflows/script.py
    - name: Checkout to destination CI-analyzes repo
      uses: actions/checkout@v3
      if: always()
      with:
        path: git-client-plugin
        ref: '1677107865-ca8de23'
        repository: 'UT-SE-Research/ci-analyzes'
        token: '${{ secrets.API_TOKEN_GITHUB }}'
        persist-credentials: true
    - name: Copy files to push to another directory
      if: always()
      run: |
        mkdir -p git-client-plugin/git-client-plugin/.github/workflows/labeler/triage
        cp -rvT optimizing-ci-builds-ci-analysis git-client-plugin/git-client-plugin/.github/workflows/labeler/triage
    - name: Pushes analysis to another repository
      if: always()
      working-directory: git-client-plugin
      run: |
        commit_message=$GITHUB_REPOSITORY@$GITHUB_WORKFLOW_SHA
        git config --global user.name 'UT-SE-Research'
        git config --global user.email '${{ secrets.EMAIL }}'
        git add .
        git commit -m $commit_message
        while ! git push -f origin 1677107865-ca8de23; do
          git pull --rebase origin 1677107865-ca8de23
          sleep $((RANDOM % 5 + 1))
        done
